# Generated by Django 2.1.2 on 2018-10-16 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='姓名')),
                ('gender', models.CharField(max_length=4, verbose_name='性别')),
                ('bith', models.DateTimeField(default=django.utils.timezone.now, verbose_name='出生日期')),
                ('start_work_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始工作的时间')),
                ('depart', models.CharField(default='技术部', max_length=30, verbose_name='部门')),
                ('salary', models.FloatField(verbose_name='底薪')),
            ],
            options={
                'verbose_name': '成员',
                'verbose_name_plural': '成员',
            },
        ),
    ]
